apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

  - ingress.yaml

namespace: hivelab-sites

images:
  - name: harbor.fedlify.com/hivelab-sites/ontario-lead-analysis
    newTag: 9b452479-3c22-4c95-b98c-c44a53278279
