apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

  - ingress.yaml

images:
  - name: harbor.fedlify.com/hivelab-static-webpage/ontario-lead-analysis
    newTag: d677a0b4-781e-413a-b35c-ab24d5e48df4
