apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

  - ingress.yaml

namespace: hivelab-sites

images:
  - name: harbor.fedlify.com/hivelab-static-webpage/ontario-lead-analysis
    newTag: branch-main
